### PR TITLE
CoffeeScript -> JS

### LINKED ISSUE #2: Peer dependency warning with Hubot 3
Installing this package together with Hubot 3 generates `warning " > hubot-ascii-art@1.1.1" has incorrect peer dependency "hubot@2.x".` I suspect that this package is compatible with Hubot 3, so a simple update of the peer dependency range should be sufficient?

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR updates all coffeescript files to JS ES6 to be compatible with Hubot 3.

Fixes #2

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+ * DS207: Consider shorter variations of null checks
+ * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
+ */
+const fs = require('fs');
+const path = require('path');
+
+module.exports = function(robot, scripts) {
+  const scriptsPath = path.resolve(__dirname, 'src');
+  if (fs.existsSync(scriptsPath)) {
+    return (() => {
```
Comment (sanderploegsma) [inline index.js]: Why return a function that is invoked immediately?

File: index.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+      const result = [];
+      for (let script of Array.from(fs.readdirSync(scriptsPath).sort())) {
+        if ((scripts != null) && !Array.from(scripts).includes('*')) {
+          if (Array.from(scripts).includes(script)) { result.push(robot.loadFile(scriptsPath, script)); } else {
+            result.push(undefined);
+          }
+        } else {
+          result.push(robot.loadFile(scriptsPath, script));
+        }
```
Comment (sanderploegsma) [inline index.js]: I think this could be reduced to

``` javascript
return fs.readdirSync(scriptsPath)
    .filter(script => scripts == null || scripts.includes('*') || scripts.includes(script))
    .map(script => robot.loadFile(scriptsPath, script));
```

Don't you think?

**Review by sanderploegsma — CHANGES_REQUESTED** [review]
Wasn't aware that Hubot dropped coffeescript support, thanks!

Code looks good except for two minor style comments. If you could address those I'd be happy to merge.

**Comment by TimvdLippe** [comment]
@sanderploegsma Thanks for the review, PR updated :tada:

**Comment by sanderploegsma** [comment]
Travis still has some issues, but I'll fix that in `master`.

**Review by sanderploegsma — APPROVED** [review]
